{% set name = "acro" %}
{% set version = "0.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cd6039fb17915d7b0c76bd4cd44e89cd5caee364bf8a31e211314931dea05d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas <=2.3.3
    - PyYAML
    - statsmodels

test:
  imports:
    - acro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AI-SDC/ACRO
  summary: "Tools for the Semi-Automatic Checking of Research Outputs"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
