{% set name = "acro" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a1ad6f0b43447730fd8a779c1c0767a8b3e5d9c3e858ad3ad8d3c5d762a881d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas >=1.5.0,<2.3
    - PyYAML
    - statsmodels
    - scipy <1.16.0

test:
  imports:
    - acro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AI-SDC/ACRO
  summary: "Tools for the Semi-Automatic Checking of Research Outputs"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
